from typing import  Any

class ABPerson:
    def valueForProperty_(self, prop: str) -> str: ...
    def setValue_forProperty_(self, value: str, prop: str) -> bool: ...

def ABPersonCreate() -> ABPerson: ...
def ABRecordSetValue(person: ABPerson, key: str, value: Any) -> bool: ...
def ABRecordCopyValue(person: ABPerson, key: str) -> Any: ...
def ABCopyArrayOfAllPeople(addr_book: Any) -> list[ABPerson]: ...
def ABGetSharedAddressBook() -> Any: ...
def ABGetMe(addr_book: Any) -> ABPerson: ...
def ABAddRecord(book: Any, person: ABPerson) -> None: ...
def ABSave(book: Any) -> None: ...

def ABMultiValueCreateMutable() -> Any: ...
def ABMultiValueInsert(mv: Any, value: str, label: str, index: int, identifier: Any) -> tuple[bool, Any]: ...
def ABMultiValueCopyValueAtIndex(mv: Any, index: int) -> str: ...
def ABMultiValueCopyLabelAtIndex(mv: Any, index: int) -> str: ...

kABFirstNameProperty: str
kABMiddleNameProperty: str
kABLastNameProperty: str
kABEmailProperty: str
kABPhoneProperty: str
kABAddressProperty: str
kABJobTitleProperty: str
kABOrganizationProperty: str
kABDepartmentProperty: str
kABSocialProfileProperty: str
kABInstantMessageProperty: str
kABBirthdayProperty: str
kABNoteProperty: str